version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: supertest
    versions:
    - 6.0.1
  - dependency-name: pug
    versions:
    - 3.0.0
